services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: "production"
      ADMIN_USERNAME: "Admin"
      ADMIN_EMAIL: "admin@mail.me"
      ADMIN_PASSWORD: "securepass"
      SECRET_KEY: "SUPERSECRETKEY"
    command: >
      sh -c "
        until npx prisma migrate deploy; do
          echo 'Waiting for database...'
          sleep 3
        done &&
        echo '✅ Database ready' &&
        npx prisma generate &&
        echo '✅ Prisma generated' &&
        echo '🚀 Starting dev server...' &&
        node dist/main.js
      "
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "securepass"