services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    environment:
      NODE_ENV: "production"
      ADMIN_USERNAME: "Admin"
      ADMIN_EMAIL: "admin@mail.me"
      ADMIN_PASSWORD: "securepass"
      SECRET_KEY: "SUPERSECRETKEY"
    command: >
      sh -c "
        until npx prisma migrate deploy; do
          echo 'Waiting for database...'
          sleep 3
        done &&
        echo '✅ Database ready' &&
        npx prisma generate &&
        echo '✅ Prisma generated' &&
        echo '🚀 Starting dev server...' &&
        node dist/main.js
      "
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - client
      - server
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do sleep 12h & wait $${!}; certbot renew; done;'"
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "securepass"