FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm ci --omit=dev --prefer-offline --no-audit --progress=false

COPY dist ./dist

COPY prisma ./prisma

COPY node_modules/.prisma ./node_modules/.prisma

COPY node_modules/@prisma ./node_modules/@prisma

EXPOSE 3001

CMD ["node", "--max-old-space-size=256", "dist/main.js"]